// js/config.js - Game Constants, Balancing, and Entity Definitions

export const MAP_CONFIG = {
  WIDTH: 70,              // Grid width in isometric tiles
  HEIGHT: 70,             // Grid height in isometric tiles
  TILE_WIDTH_HALF: 32,    // Half width of isometric tile in screen pixels
  TILE_HEIGHT_HALF: 16,   // Half height of isometric tile in screen pixels
};

export const STARTING_RESOURCES = {
  FUNDS: 1200,            // Starting Cash ($)
  TECH_SUPPLIES: 150,     // Starting Tech Crates
  POWER_PRODUCTION: 60,   // Base MW
  POWER_CONSUMPTION: 10,
};

export const HERO_CONFIG = {
  name: "Commander Vanguard",
  hp: 850,
  maxHp: 850,
  energy: 100,
  maxEnergy: 100,
  energyRegen: 4.5,       // Per second
  speed: 2.8,
  range: 5.8,
  damage: 34,
  attackRate: 0.3,        // Seconds between shots (rapid burst assault rifle)
  sightRadius: 9,
  xpToLevel: [100, 250, 450, 700, 1050, 1500, 2100, 2800, 3600, 4600],
  abilities: {
    q: {
      id: "recon",
      name: "Recon Drone Scan",
      key: "Q",
      cooldown: 18,
      energyCost: 20,
      radius: 8,
      duration: 14,
      description: "Launches an orbital recon drone that permanently sweeps fog of war in target area for 14s.",
    },
    w: {
      id: "sentry",
      name: "Deploy Sentry Turret",
      key: "W",
      cooldown: 30,
      energyCost: 35,
      duration: 35,
      description: "Airdrops a rapid-fire 25mm automated sentry gun that shreds approaching infantry.",
    },
    e: {
      id: "medevac",
      name: "Field Medevac / Nanorepair",
      key: "E",
      cooldown: 28,
      energyCost: 30,
      radius: 5.5,
      healAmount: 320,
      description: "Deploys a nanotech repair aura healing the Hero and all nearby allied units and vehicles.",
    },
    r: {
      id: "missile",
      name: "Tactical Cruise Missile",
      key: "R",
      cooldown: 48,
      energyCost: 55,
      radius: 3.5,
      damage: 550,
      description: "Targeted orbital cruise missile that strikes with catastrophic explosive blast radius.",
    },
  },
};

export const BUILDINGS_CONFIG = {
  hq: {
    id: "hq",
    name: "Command HQ",
    w: 3,
    h: 3,
    hp: 2800,
    cost: 0,
    techCost: 0,
    power: 60,
    passiveIncome: 25,     // Funds per second
    sightRadius: 11,
    description: "Core Operations Center. Provides base command, passive cashflow ($25/s), and unlocks primary tech.",
  },
  power: {
    id: "power",
    name: "Solar Power Reactor",
    w: 2,
    h: 2,
    hp: 1100,
    cost: 220,
    techCost: 20,
    power: 120,            // +120 MW
    passiveIncome: 0,
    sightRadius: 6,
    description: "High-yield power generator. Supplies +120 MW to operate radar grids, factory assembly lines, and defenses.",
  },
  barracks: {
    id: "barracks",
    name: "Infantry Barracks",
    w: 2,
    h: 2,
    hp: 1300,
    cost: 320,
    techCost: 30,
    power: -20,
    sightRadius: 7,
    trains: ["rifleman", "sniper", "rpg"],
    description: "Recruitment training compound for Spec-Ops Riflemen, Heavy Snipers, and Anti-Tank RPG Operators.",
  },
  factory: {
    id: "factory",
    name: "War Factory",
    w: 3,
    h: 3,
    hp: 2200,
    cost: 650,
    techCost: 80,
    power: -45,
    sightRadius: 8,
    trains: ["buggy", "tank", "artillery"],
    description: "Heavy vehicular assembly plant. Produces fast Combat Buggies, Main Battle Tanks, and Rocket Artillery.",
  },
  helipad: {
    id: "helipad",
    name: "Tactical Airfield",
    w: 3,
    h: 3,
    hp: 1600,
    cost: 550,
    techCost: 90,
    power: -35,
    sightRadius: 8,
    trains: ["chopper"],
    description: "Helipad and UAV hangar. Constructs and launches airborne Apache Gunships.",
  },
  trade: {
    id: "trade",
    name: "Trade Exchange Hub",
    w: 2,
    h: 2,
    hp: 1400,
    cost: 420,
    techCost: 40,
    power: -20,
    passiveIncome: 18,
    sightRadius: 7,
    description: "International military trade depot. Generates passive trading revenue and opens dynamic resource exchange.",
  },
  turret: {
    id: "turret",
    name: "Minigun Pillbox",
    w: 1,
    h: 1,
    hp: 850,
    cost: 260,
    techCost: 30,
    power: -25,
    sightRadius: 8,
    attackRange: 6.2,
    damage: 16,
    attackRate: 0.18,      // High rate of fire
    bulletSpeed: 14,
    description: "Automated 25mm twin-gatling gun turret. Lethal against hostile infantry and light strike buggies.",
  },
  sam: {
    id: "sam",
    name: "SAM Missile Launcher",
    w: 2,
    h: 2,
    hp: 1050,
    cost: 480,
    techCost: 65,
    power: -40,
    sightRadius: 9,
    attackRange: 8.5,
    damage: 120,
    attackRate: 1.8,
    aoe: 1.2,
    bulletSpeed: 9,
    description: "Heavy surface missile battery. Delivers explosive anti-armor and surface-to-air guided munitions.",
  },
};

export const UNITS_CONFIG = {
  rifleman: {
    id: "rifleman",
    name: "Spec-Ops Soldier",
    category: "infantry",
    hp: 160,
    maxHp: 160,
    speed: 2.4,
    range: 4.8,
    damage: 18,
    attackRate: 0.38,
    cost: 85,
    techCost: 0,
    trainTime: 4.5,
    sightRadius: 6.5,
    description: "Rapid assault infantry armed with modern M4 carbine.",
  },
  sniper: {
    id: "sniper",
    name: "Elite Marksman",
    category: "infantry",
    hp: 100,
    maxHp: 100,
    speed: 2.1,
    range: 8.8,
    damage: 105,
    attackRate: 1.7,
    cost: 160,
    techCost: 20,
    trainTime: 7.0,
    sightRadius: 9.5,
    description: "Long-range anti-personnel sniper. High critical damage.",
  },
  rpg: {
    id: "rpg",
    name: "Anti-Armor Specialist",
    category: "infantry",
    hp: 140,
    maxHp: 140,
    speed: 2.0,
    range: 6.2,
    damage: 85,
    attackRate: 1.3,
    aoe: 1.2,
    cost: 140,
    techCost: 25,
    trainTime: 6.5,
    sightRadius: 6.5,
    description: "Shoulder-fired RPG rocketeer. Punishes armored vehicles and groups.",
  },
  buggy: {
    id: "buggy",
    name: "Fast Attack Buggy",
    category: "vehicle",
    hp: 380,
    maxHp: 380,
    speed: 3.6,
    range: 5.2,
    damage: 24,
    attackRate: 0.25,
    cost: 270,
    techCost: 35,
    trainTime: 7.5,
    sightRadius: 7.5,
    description: "Fast-moving all-terrain recon vehicle with mounted twin heavy machine guns.",
  },
  tank: {
    id: "tank",
    name: "Abrams Battle Tank",
    category: "vehicle",
    hp: 980,
    maxHp: 980,
    speed: 1.85,
    range: 6.8,
    damage: 135,
    attackRate: 1.6,
    aoe: 1.5,
    cost: 580,
    techCost: 90,
    trainTime: 13.0,
    sightRadius: 7.5,
    description: "Heavy armor with a 120mm smoothbore cannon. Destroys fortifications and columns.",
  },
  artillery: {
    id: "artillery",
    name: "Mobile MLRS Artillery",
    category: "vehicle",
    hp: 420,
    maxHp: 420,
    speed: 1.5,
    range: 10.5,
    damage: 175,
    attackRate: 2.8,
    aoe: 2.4,
    cost: 720,
    techCost: 110,
    trainTime: 16.0,
    sightRadius: 8.0,
    description: "Multiple launch rocket system. Devastating siege bombardment from far away.",
  },
  chopper: {
    id: "chopper",
    name: "AH-64 Apache Gunship",
    category: "air",
    isFlying: true,
    hp: 520,
    maxHp: 520,
    speed: 3.7,
    range: 5.8,
    damage: 42,
    attackRate: 0.38,
    cost: 680,
    techCost: 120,
    trainTime: 14.0,
    sightRadius: 9.0,
    description: "High-speed air attack helicopter armed with 30mm chain gun and Hydra rockets. Ignores terrain.",
  },
};

export const ENEMY_UNITS_CONFIG = {
  enemy_scout: {
    name: "Insurgent Scout",
    category: "infantry",
    hp: 120,
    maxHp: 120,
    speed: 2.5,
    range: 4.5,
    damage: 14,
    attackRate: 0.45,
    sightRadius: 6,
    bounty: 30,
    techBounty: 5,
  },
  enemy_militia: {
    name: "Rogue Militiaman",
    category: "infantry",
    hp: 160,
    maxHp: 160,
    speed: 2.3,
    range: 4.8,
    damage: 18,
    attackRate: 0.4,
    sightRadius: 6,
    bounty: 45,
    techBounty: 8,
  },
  enemy_rpg: {
    name: "Hostile RPG Mercenary",
    category: "infantry",
    hp: 130,
    maxHp: 130,
    speed: 2.0,
    range: 5.8,
    damage: 75,
    attackRate: 1.4,
    aoe: 1.2,
    sightRadius: 6,
    bounty: 60,
    techBounty: 12,
  },
  enemy_technical: {
    name: "Armored Technical Truck",
    category: "vehicle",
    hp: 350,
    maxHp: 350,
    speed: 3.3,
    range: 5.0,
    damage: 22,
    attackRate: 0.3,
    sightRadius: 7,
    bounty: 110,
    techBounty: 20,
  },
  enemy_tank: {
    name: "Shadow Heavy Tank",
    category: "vehicle",
    hp: 920,
    maxHp: 920,
    speed: 1.7,
    range: 6.5,
    damage: 125,
    attackRate: 1.7,
    aoe: 1.5,
    sightRadius: 7,
    bounty: 220,
    techBounty: 45,
  },
  enemy_chopper: {
    name: "Rogue Gunship Drone",
    category: "air",
    isFlying: true,
    hp: 440,
    maxHp: 440,
    speed: 3.5,
    range: 5.5,
    damage: 34,
    attackRate: 0.42,
    sightRadius: 8,
    bounty: 180,
    techBounty: 40,
  },
};

export const TRADE_CONFIG = {
  BUY_TECH_RATE: 1.8,       // $1.80 per 1 Tech Supply
  SELL_TECH_RATE: 1.1,      // $1.10 received per 1 Tech Supply
  AIRSTRIKE_BUY_COST: 600,  // Buy instant cruise missile voucher
  MERCENARY_SQUAD_COST: 450,// Instant 3 elite soldiers airdrop
  EMERGENCY_CASH_PACK: 500, // 300 Tech for $500
};

export const INVASION_CONFIG = {
  INITIAL_DELAY: 60,        // 60 seconds before Wave 1
  TIME_BETWEEN_WAVES: 65,   // 65 seconds between subsequent waves
  WARNING_DURATION: 20,     // Warning siren countdown 20s prior to wave
};
