// js/config.js - Game Constants, Balancing, and Entity Definitions

export const MAP_CONFIG = {
  WIDTH: 70,              // Grid width in isometric tiles
  HEIGHT: 70,             // Grid height in isometric tiles
  TILE_WIDTH_HALF: 32,    // Half width of isometric tile in screen pixels
  TILE_HEIGHT_HALF: 16,   // Half height of isometric tile in screen pixels
};

export const STARTING_RESOURCES = {
  FUNDS: 2500,            // Generous starting Cash ($)
  TECH_SUPPLIES: 350,     // Starting Tech Crates
  POWER_PRODUCTION: 120,  // Base MW
  POWER_CONSUMPTION: 10,
};

export const HERO_CONFIG = {
  name: "Commander Vanguard",
  hp: 950,
  maxHp: 950,
  energy: 100,
  maxEnergy: 100,
  energyRegen: 5.0,       // Per second
  speed: 3.0,
  range: 6.0,
  damage: 38,
  attackRate: 0.28,       // Seconds between shots (rapid burst assault rifle)
  sightRadius: 10,
  xpToLevel: [100, 250, 450, 700, 1050, 1500, 2100, 2800, 3600, 4600],
  abilities: {
    q: {
      id: "recon",
      name: "Recon Drone Scan",
      key: "Q",
      cooldown: 16,
      energyCost: 20,
      radius: 9,
      duration: 16,
      description: "Launches an orbital recon drone that permanently sweeps fog of war in target area for 16s.",
    },
    w: {
      id: "sentry",
      name: "Deploy Sentry Turret",
      key: "W",
      cooldown: 28,
      energyCost: 35,
      duration: 40,
      description: "Airdrops a rapid-fire 25mm automated sentry gun that shreds approaching infantry.",
    },
    e: {
      id: "medevac",
      name: "Field Medevac / Nanorepair",
      key: "E",
      cooldown: 24,
      energyCost: 30,
      radius: 6.0,
      healAmount: 380,
      description: "Deploys a nanotech repair aura healing the Hero and all nearby allied units and vehicles.",
    },
    r: {
      id: "missile",
      name: "Tactical Cruise Missile",
      key: "R",
      cooldown: 42,
      energyCost: 50,
      radius: 4.0,
      damage: 650,
      description: "Targeted orbital cruise missile that strikes with catastrophic explosive blast radius.",
    },
  },
};

export const BUILDINGS_CONFIG = {
  hq: {
    id: "hq",
    name: "Command HQ",
    w: 3,
    h: 3,
    hp: 3200,
    cost: 0,
    techCost: 0,
    power: 80,
    passiveIncome: 30,     // Funds per second
    sightRadius: 12,
    trains: ["worker"],
    description: "Core Operations Center. Provides base command, trains Civilian Farmers/Workers, passive cashflow ($30/s), and unlocks primary tech.",
  },
  farm: {
    id: "farm",
    name: "Agricultural Farm",
    w: 2,
    h: 2,
    hp: 1100,
    cost: 140,
    techCost: 0,
    power: 0,
    sightRadius: 6,
    passiveIncome: 16,     // Funds per second from crops/food
    trains: ["worker"],
    description: "Cultivated crop farm with automated irrigation. Produces sustainable food & cash yields ($16/s). Train farmers to boost yields!",
  },
  power: {
    id: "power",
    name: "Solar Power Reactor",
    w: 2,
    h: 2,
    hp: 1200,
    cost: 200,
    techCost: 15,
    power: 140,            // +140 MW
    passiveIncome: 0,
    sightRadius: 7,
    description: "High-yield power generator. Supplies +140 MW to operate radar grids, factory assembly lines, and defenses.",
  },
  barracks: {
    id: "barracks",
    name: "Infantry Barracks",
    w: 2,
    h: 2,
    hp: 1400,
    cost: 280,
    techCost: 20,
    power: -20,
    sightRadius: 7,
    trains: ["worker", "rifleman", "sniper", "rpg"],
    description: "Recruitment training compound for Spec-Ops Riflemen, Heavy Snipers, and Anti-Tank RPG Operators.",
  },
  factory: {
    id: "factory",
    name: "War Factory",
    w: 3,
    h: 3,
    hp: 2400,
    cost: 580,
    techCost: 60,
    power: -40,
    sightRadius: 8,
    trains: ["buggy", "tank", "artillery"],
    description: "Heavy vehicular assembly plant. Produces fast Combat Buggies, Main Battle Tanks, and Rocket Artillery.",
  },
  helipad: {
    id: "helipad",
    name: "Tactical Airfield",
    w: 3,
    h: 3,
    hp: 1800,
    cost: 500,
    techCost: 75,
    power: -30,
    sightRadius: 9,
    trains: ["chopper"],
    description: "Helipad and UAV hangar. Constructs and launches airborne Apache Gunships.",
  },
  trade: {
    id: "trade",
    name: "Trade Exchange Hub",
    w: 2,
    h: 2,
    hp: 1500,
    cost: 380,
    techCost: 35,
    power: -15,
    passiveIncome: 22,
    sightRadius: 7,
    description: "International military trade depot. Generates passive trading revenue and opens dynamic resource exchange.",
  },
  turret: {
    id: "turret",
    name: "Minigun Pillbox",
    w: 1,
    h: 1,
    hp: 950,
    cost: 220,
    techCost: 20,
    power: -20,
    sightRadius: 8,
    attackRange: 6.5,
    damage: 18,
    attackRate: 0.16,
    bulletSpeed: 16,
    description: "Automated 25mm twin-gatling gun turret. Lethal against hostile infantry and light strike buggies.",
  },
  sam: {
    id: "sam",
    name: "SAM Missile Launcher",
    w: 2,
    h: 2,
    hp: 1100,
    cost: 420,
    techCost: 50,
    power: -35,
    sightRadius: 9,
    attackRange: 8.8,
    damage: 130,
    attackRate: 1.7,
    aoe: 1.3,
    bulletSpeed: 10,
    description: "Heavy surface missile battery. Delivers explosive anti-armor and surface-to-air guided munitions.",
  },
};

export const UNITS_CONFIG = {
  worker: {
    id: "worker",
    name: "Civilian Farmer / Worker",
    category: "civilian",
    hp: 130,
    maxHp: 130,
    speed: 2.3,
    range: 2.2,
    damage: 15,
    attackRate: 0.6,
    cost: 50,
    techCost: 0,
    trainTime: 2.5,
    sightRadius: 6.5,
    description: "Civilian farmer & laborer. Cultivates agricultural farms (+harvest cashflow) and automatically repairs damaged buildings.",
  },
  rifleman: {
    id: "rifleman",
    name: "Spec-Ops Soldier",
    category: "infantry",
    hp: 180,
    maxHp: 180,
    speed: 2.6,
    range: 5.0,
    damage: 20,
    attackRate: 0.35,
    cost: 75,
    techCost: 0,
    trainTime: 3.5,
    sightRadius: 7.0,
    description: "Rapid assault infantry armed with modern M4 carbine.",
  },
  sniper: {
    id: "sniper",
    name: "Elite Marksman",
    category: "infantry",
    hp: 110,
    maxHp: 110,
    speed: 2.3,
    range: 9.0,
    damage: 115,
    attackRate: 1.5,
    cost: 140,
    techCost: 15,
    trainTime: 5.5,
    sightRadius: 10.0,
    description: "Long-range anti-personnel sniper. High critical damage.",
  },
  rpg: {
    id: "rpg",
    name: "Anti-Armor Specialist",
    category: "infantry",
    hp: 150,
    maxHp: 150,
    speed: 2.2,
    range: 6.5,
    damage: 90,
    attackRate: 1.2,
    aoe: 1.3,
    cost: 120,
    techCost: 20,
    trainTime: 5.0,
    sightRadius: 7.0,
    description: "Shoulder-fired RPG rocketeer. Punishes armored vehicles and groups.",
  },
  buggy: {
    id: "buggy",
    name: "Fast Attack Buggy",
    category: "vehicle",
    hp: 400,
    maxHp: 400,
    speed: 3.8,
    range: 5.4,
    damage: 26,
    attackRate: 0.22,
    cost: 240,
    techCost: 30,
    trainTime: 6.0,
    sightRadius: 8.0,
    description: "Fast-moving all-terrain recon vehicle with mounted twin heavy machine guns.",
  },
  tank: {
    id: "tank",
    name: "Abrams Battle Tank",
    category: "vehicle",
    hp: 1050,
    maxHp: 1050,
    speed: 2.0,
    range: 7.0,
    damage: 145,
    attackRate: 1.5,
    aoe: 1.6,
    cost: 520,
    techCost: 75,
    trainTime: 10.0,
    sightRadius: 8.0,
    description: "Heavy armor with a 120mm smoothbore cannon. Destroys fortifications and columns.",
  },
  artillery: {
    id: "artillery",
    name: "Mobile MLRS Artillery",
    category: "vehicle",
    hp: 450,
    maxHp: 450,
    speed: 1.6,
    range: 11.0,
    damage: 185,
    attackRate: 2.6,
    aoe: 2.5,
    cost: 650,
    techCost: 95,
    trainTime: 12.0,
    sightRadius: 8.5,
    description: "Multiple launch rocket system. Devastating siege bombardment from far away.",
  },
  chopper: {
    id: "chopper",
    name: "AH-64 Apache Gunship",
    category: "air",
    isFlying: true,
    hp: 550,
    maxHp: 550,
    speed: 4.0,
    range: 6.0,
    damage: 46,
    attackRate: 0.35,
    cost: 620,
    techCost: 100,
    trainTime: 11.0,
    sightRadius: 9.5,
    description: "High-speed air attack helicopter armed with 30mm chain gun and Hydra rockets. Ignores terrain.",
  },
};

export const ENEMY_UNITS_CONFIG = {
  enemy_scout: {
    name: "Insurgent Scout",
    category: "infantry",
    hp: 120,
    maxHp: 120,
    speed: 2.5,
    range: 4.5,
    damage: 14,
    attackRate: 0.45,
    sightRadius: 6,
    bounty: 35,
    techBounty: 6,
  },
  enemy_militia: {
    name: "Rogue Militiaman",
    category: "infantry",
    hp: 160,
    maxHp: 160,
    speed: 2.3,
    range: 4.8,
    damage: 18,
    attackRate: 0.4,
    sightRadius: 6,
    bounty: 50,
    techBounty: 10,
  },
  enemy_rpg: {
    name: "Hostile RPG Mercenary",
    category: "infantry",
    hp: 130,
    maxHp: 130,
    speed: 2.0,
    range: 5.8,
    damage: 75,
    attackRate: 1.4,
    aoe: 1.2,
    sightRadius: 6,
    bounty: 65,
    techBounty: 14,
  },
  enemy_technical: {
    name: "Armored Technical Truck",
    category: "vehicle",
    hp: 350,
    maxHp: 350,
    speed: 3.3,
    range: 5.0,
    damage: 22,
    attackRate: 0.3,
    sightRadius: 7,
    bounty: 120,
    techBounty: 24,
  },
  enemy_tank: {
    name: "Shadow Heavy Tank",
    category: "vehicle",
    hp: 920,
    maxHp: 920,
    speed: 1.7,
    range: 6.5,
    damage: 125,
    attackRate: 1.7,
    aoe: 1.5,
    sightRadius: 7,
    bounty: 240,
    techBounty: 50,
  },
  enemy_chopper: {
    name: "Rogue Gunship Drone",
    category: "air",
    isFlying: true,
    hp: 440,
    maxHp: 440,
    speed: 3.5,
    range: 5.5,
    damage: 34,
    attackRate: 0.42,
    sightRadius: 8,
    bounty: 190,
    techBounty: 45,
  },
};

export const TRADE_CONFIG = {
  BUY_TECH_RATE: 1.6,       // $1.60 per 1 Tech Supply
  SELL_TECH_RATE: 1.2,      // $1.20 received per 1 Tech Supply
  AIRSTRIKE_BUY_COST: 550,  // Buy instant cruise missile voucher
  MERCENARY_SQUAD_COST: 400,// Instant 3 elite soldiers airdrop
  EMERGENCY_CASH_PACK: 500, // 300 Tech for $500
};

export const INVASION_CONFIG = {
  INITIAL_DELAY: 300,       // 5 FULL MINUTES of peaceful base building and army raising!
  TIME_BETWEEN_WAVES: 120,  // 2 minutes between subsequent waves
  WARNING_DURATION: 25,     // Warning siren countdown 25s prior to wave
};
